name: flutter_ytim_example
description: "Demonstrates how to use the flutter_ytim plugin."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_ytim:
    path: ../


  cupertino_icons: ^1.0.6
  dio: ^5.3.0
  flutter_slidable: ^3.0.1
  audioplayers: ^6.0.0
  photo_view: ^0.15.0
  saver_gallery: ^3.0.1
  video_player: ^2.8.1
  image_picker: ^1.0.5
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.5
  flutter_easyloading: ^3.0.5
  xbr_plugin_record: ^1.0.2
  easy_refresh: ^3.3.4
  event_bus_plus: ^0.6.1
  image_cropper: ^5.0.0
  image: ^4.1.3
  page_transition: ^2.0.9

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/imIcons/
    - assets/imIcons/im/
    - assets/svg/
