name: flutter_ytim
description: YouTeacher IM SDK for Flutter. Help you quickly integrate YTIM into your project.
version: 3.0.0
homepage: https://github.com/and2long/flutter_ytim

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^2.4.0
  dio: ^5.1.2
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  crypto: ^3.0.3
  connectivity_plus: ^6.0.2
  pull_to_refresh: ^2.0.0
  flutter_slidable: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.21.4


flutter:
  uses-material-design: true
