name: flutter_ytim
description: YouTeacher IM SDK for Flutter. Help you quickly integrate YTIM into your project.
version: 2.5.0
homepage: https://github.com/and2long/flutter_ytim

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^2.1.0
  dio: ^4.0.4
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  crypto: ^3.0.1
  connectivity_plus: ^2.2.0
  pull_to_refresh: ^2.0.0
  flutter_slidable: ^1.2.0