name: flutter_ytim
description: YouTeacher IM SDK for Flutter. Help you quickly integrate YTIM into your project.

version: 2.5.5
homepage: https://github.com/and2long/flutter_ytim

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^2.4.0
  dio: ^5.1.2
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  crypto: ^3.0.3
  connectivity_plus: ^4.0.1
  pull_to_refresh: ^2.0.0
  flutter_slidable: ^3.0.0

dev_dependencies:
  test: ^1.21.4

flutter:
  uses-material-design: true