name: flutter_ytim
description: YouTeacher IM SDK for Flutter. Help you quickly integrate YTIM into your project.
version: 2.1.4
homepage: https://github.com/and2long/flutter_ytim

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^2.0.0
  dio: ^4.0.0
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  crypto: ^3.0.1
  connectivity: ^3.0.3
  pull_to_refresh: ^2.0.0